In [1]:
import numpy as np
from sklearn import datasets

In [3]:
iris=datasets.load_iris()

In [5]:
iris.data.shape

(150, 4)

In [13]:
target = iris.target.reshape

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [14]:
iris_all = np.hstack([iris.data,iris.target.reshape(-1,1)])

In [21]:
iris_all_shuffle = np.random.permutation(iris_all)
iris_all_shuffle

array([[5.5, 2.4, 3.8, 1.1, 1. ],
       [7.4, 2.8, 6.1, 1.9, 2. ],
       [5.1, 3.8, 1.6, 0.2, 0. ],
       [5.5, 3.5, 1.3, 0.2, 0. ],
       [5.1, 3.4, 1.5, 0.2, 0. ],
       [6.1, 2.6, 5.6, 1.4, 2. ],
       [6.7, 3.3, 5.7, 2.5, 2. ],
       [6.5, 3. , 5.8, 2.2, 2. ],
       [5.6, 2.8, 4.9, 2. , 2. ],
       [5.4, 3.4, 1.5, 0.4, 0. ],
       [5.1, 3.3, 1.7, 0.5, 0. ],
       [6.2, 2.2, 4.5, 1.5, 1. ],
       [5.2, 4.1, 1.5, 0.1, 0. ],
       [4.7, 3.2, 1.6, 0.2, 0. ],
       [5.1, 2.5, 3. , 1.1, 1. ],
       [5.4, 3.9, 1.7, 0.4, 0. ],
       [5. , 3.6, 1.4, 0.2, 0. ],
       [6.4, 2.8, 5.6, 2.2, 2. ],
       [7.2, 3. , 5.8, 1.6, 2. ],
       [4.8, 3.4, 1.6, 0.2, 0. ],
       [7.1, 3. , 5.9, 2.1, 2. ],
       [6.7, 2.5, 5.8, 1.8, 2. ],
       [5.5, 4.2, 1.4, 0.2, 0. ],
       [5.8, 2.7, 5.1, 1.9, 2. ],
       [6. , 2.9, 4.5, 1.5, 1. ],
       [6.8, 2.8, 4.8, 1.4, 1. ],
       [6.3, 3.4, 5.6, 2.4, 2. ],
       [5.2, 2.7, 3.9, 1.4, 1. ],
       [7.6, 3. , 6.6, 2.1, 2. ],
       [6.8, 3

In [23]:
X = iris_all_shuffle[:, :-1]

In [47]:
Y = iris_all_shuffle[:, -1]
Y

array([1., 2., 0., 0., 0., 2., 2., 2., 2., 0., 0., 1., 0., 0., 1., 0., 0.,
       2., 2., 0., 2., 2., 0., 2., 1., 1., 2., 1., 2., 2., 2., 1., 2., 2.,
       1., 0., 0., 1., 2., 1., 0., 1., 0., 1., 2., 1., 0., 2., 0., 2., 1.,
       0., 0., 2., 0., 1., 0., 1., 0., 1., 1., 1., 2., 0., 1., 1., 0., 2.,
       1., 2., 2., 1., 2., 2., 1., 0., 0., 0., 2., 0., 2., 2., 1., 2., 0.,
       0., 2., 2., 0., 2., 0., 0., 0., 0., 1., 2., 1., 2., 2., 0., 1., 1.,
       2., 1., 2., 1., 2., 0., 2., 2., 1., 2., 2., 1., 0., 1., 0., 1., 0.,
       0., 0., 0., 0., 2., 2., 1., 0., 1., 0., 0., 2., 1., 1., 1., 1., 2.,
       1., 0., 2., 0., 1., 1., 1., 1., 2., 1., 1., 1., 0., 1.])

In [38]:
test_size = int(len(iris_all_shuffle) * 0.2)
test_size

30

In [40]:
X_test = X[:test_size,:]
X_train = X[test_size:,:]
X_train,X_test

(array([[6.7, 3. , 5.2, 2.3],
        [6.7, 3.1, 4.4, 1.4],
        [6. , 2.2, 5. , 1.5],
        [5.8, 2.7, 5.1, 1.9],
        [5.6, 3. , 4.1, 1.3],
        [4.9, 3.6, 1.4, 0.1],
        [4.8, 3.4, 1.9, 0.2],
        [5.5, 2.3, 4. , 1.3],
        [6.5, 3. , 5.5, 1.8],
        [6.2, 2.9, 4.3, 1.3],
        [4.9, 3.1, 1.5, 0.2],
        [6. , 2.7, 5.1, 1.6],
        [4.6, 3.1, 1.5, 0.2],
        [6.3, 2.3, 4.4, 1.3],
        [7.7, 3. , 6.1, 2.3],
        [5.5, 2.4, 3.7, 1. ],
        [5. , 3. , 1.6, 0.2],
        [6.2, 2.8, 4.8, 1.8],
        [4.4, 3. , 1.3, 0.2],
        [6.3, 2.7, 4.9, 1.8],
        [6.4, 3.2, 4.5, 1.5],
        [5.1, 3.8, 1.9, 0.4],
        [5. , 3.3, 1.4, 0.2],
        [7.7, 2.6, 6.9, 2.3],
        [5. , 3.5, 1.3, 0.3],
        [6.3, 2.5, 4.9, 1.5],
        [5. , 3.2, 1.2, 0.2],
        [6.3, 3.3, 4.7, 1.6],
        [5.3, 3.7, 1.5, 0.2],
        [6.4, 2.9, 4.3, 1.3],
        [6.1, 2.8, 4. , 1.3],
        [5.8, 2.7, 3.9, 1.2],
        [6.1, 3. , 4.9, 1.8],
        [5

In [48]:
Y_test = Y[:test_size]
Y_train = Y[test_size:]
Y_train,Y_test

(array([2., 1., 2., 2., 1., 0., 0., 1., 2., 1., 0., 1., 0., 1., 2., 1., 0.,
        2., 0., 2., 1., 0., 0., 2., 0., 1., 0., 1., 0., 1., 1., 1., 2., 0.,
        1., 1., 0., 2., 1., 2., 2., 1., 2., 2., 1., 0., 0., 0., 2., 0., 2.,
        2., 1., 2., 0., 0., 2., 2., 0., 2., 0., 0., 0., 0., 1., 2., 1., 2.,
        2., 0., 1., 1., 2., 1., 2., 1., 2., 0., 2., 2., 1., 2., 2., 1., 0.,
        1., 0., 1., 0., 0., 0., 0., 0., 2., 2., 1., 0., 1., 0., 0., 2., 1.,
        1., 1., 1., 2., 1., 0., 2., 0., 1., 1., 1., 1., 2., 1., 1., 1., 0.,
        1.]),
 array([1., 2., 0., 0., 0., 2., 2., 2., 2., 0., 0., 1., 0., 0., 1., 0., 0.,
        2., 2., 0., 2., 2., 0., 2., 1., 1., 2., 1., 2., 2.]))