In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
from sklearn import datasets

digits = datasets.load_digits()
X = digits.data
y = digits.target.copy()

y[digits.target==9] = 1
y[digits.target!=9] = 0

In [3]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=666)

In [4]:
from sklearn.linear_model import LogisticRegression

log_reg = LogisticRegression()
log_reg.fit(X_train, y_train)
y_predict = log_reg.predict(X_test)

/Users/yanchao/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [5]:
from sklearn.metrics import f1_score

f1_score(y_test, y_predict)

0.8674698795180723

In [6]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, y_predict)

array([[403,   2],
       [  9,  36]])

In [7]:
from sklearn.metrics import precision_score

precision_score(y_test, y_predict)

0.9473684210526315

In [8]:
from sklearn.metrics import recall_score

recall_score(y_test, y_predict)

0.8

In [9]:
log_reg.decision_function(X_test)[:10]

array([-21.41381418, -32.89620032, -16.38512811, -79.8109302 ,
       -48.0559543 , -24.19810725, -44.58538979, -24.27519547,
        -1.14004188, -18.99830583])

In [11]:
log_reg.predict(X_test)[:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
decision_scores = log_reg.decision_function(X_test)

In [13]:
np.min(decision_scores)

-85.69918410019393

In [14]:
np.max(decision_scores)

19.858355180431545

In [17]:
y_predict_2 = np.array(decision_scores >= 5, dtype='int')

In [18]:
confusion_matrix(y_test, y_predict_2)

array([[404,   1],
       [ 21,  24]])

In [19]:
precision_score(y_test, y_predict_2)

0.96

In [20]:
recall_score(y_test, y_predict_2)

0.5333333333333333

In [21]:
y_predict_3 = np.array(decision_scores >= -5, dtype='int')

In [22]:
confusion_matrix(y_test, y_predict_3)

array([[390,  15],
       [  5,  40]])

In [23]:
precision_score(y_test, y_predict_3)

0.7272727272727273

In [24]:
recall_score(y_test, y_predict_3)

0.8888888888888888